#!/bin/bash

echo "======================================"
echo "Token 刷新流程测试"
echo "======================================"
echo ""
echo "请按照以下步骤测试："
echo ""
echo "1. 启动开发服务器："
echo "   npm run dev"
echo ""
echo "2. 打开浏览器访问："
echo "   http://localhost:5173"
echo ""
echo "3. 打开浏览器控制台（F12）"
echo ""
echo "4. 登录系统"
echo ""
echo "5. 刷新页面（F5）"
echo ""
echo "6. 观察控制台日志，应该看到："
echo "   [App Init] 尝试静默刷新 Token..."
echo "   [App Init] 刷新接口完整响应: ..."
echo "   [App Init] ✅ 静默刷新成功，恢复登录态"
echo "   [Layout] 开始加载购物车数据"
echo "   [API Request] 已添加 Token: ..."
echo ""
echo "7. 验证结果："
echo "   ✅ 页面保持登录状态"
echo "   ✅ 用户信息正常显示"
echo "   ✅ 购物车数量正常显示"
echo "   ✅ 没有 '用户未登录' 错误"
echo ""
echo "详细测试指南请查看: test-token-flow.md"
echo "======================================"
